/**
 * Created by mac on 2017/2/7.
 */
export const USER_INFO_KEY = "USER_INFO";
export const PROVINCE_INFO_KEY = "PROVINCE_INFO";

//export const APP_SERVER_URL = "http://192.168.100.163:29090/api";
// export const APP_SERVER_URL = "http://192.168.100.163:29091/api";
 export const APP_SERVER_URL = "http://localhost:8080/api";


export const ACTION_TYPES = {
    USER_LOGIN : 'USER_LOGIN',
    CHANGE_PROVINCE:'CHANGE_PROVINCE',
    GET_PROVINCE_INFO:'GET_PROVINCE_INFO',
    GET_PROVINCE_BY_IP:'GET_PROVINCE_BY_IP',
    CHANGE_LOGIN_STATE:'CHANGE_LOGIN_STATE',
    GET_BONUS_POINTS:'GET_BONUS_POINTS',
    PAY_RECS:"PAY_RECS",
    USER_LOGOUT:'USER_LOGOUT',
    GET_CITY_LIST:'GET_CITY_LIST',
    GET_ACTIVITIES:'GET_ACTIVITIES',
    GET_ALL_BUNIS:"GET_ALL_BUNIS",
    GET_CHARGE:"GET_CHARGE",
    GET_HISTORY_BILL:"GET_HISTORY_BILL",
    GET_PACKAGES_REMAIN:'GET_PACKAGES_REMAIN',
    GET_ACTIVITY_LIST:"GET_ACTIVITY_LIST",
    GET_CONSUM_INFOR:'GET_CONSUM_INFOR',
    GET_LOGIN_INFO:'GET_LOGIN_INFO',
    GET_USER_MOBILE:'GET_USER_MOBILE',
    GET_USER_INFO:'GET_USER_INFO',
    GET_BILL_INFOR:'GET_BILL_INFOR',
    GET_HOME_CONFS:'GET_HOME_CONFS',
    GET_TAB_SLIDER:'GET_TAB_SLIDER',
    GET_MAIN_PLANS:'GET_MAIN_PLANS',
    GET_BANNERS:'GET_BANNERS',
    GET_BONUS_POINTS_RECORDS:'GET_BONUS_POINTS_RECORDS',
    GET_UNIS:'GET_UNIS',
    GET_NO_LOGIN_ERR_MSG:'GET_NO_LOGIN_ERR_MSG',
    GET_UNSCRIBE:'GET_UNSCRIBE',
    GET_CLEAR:"GET_CLEAR"
};



